

####

GET http://localhost:3000/product/search?keyword=lap&brand=&type=&priceL=0&priceH=10000000

#######


DELETE http://localhost:3000/product/deleteAll

#####

GET http://localhost:3000/product/createProduct